apiVersion: scheduling.x-k8s.io/v1alpha1
kind: ElasticQuota
metadata:
  name: tenant1
  namespace: tenant1
spec:
  max:
    cpu: 384
    memory: 1536G
  min:
    cpu: 128
    memory: 512G
---
apiVersion: scheduling.x-k8s.io/v1alpha1
kind: ElasticQuota
metadata:
  name: tenant2
  namespace: tenant2
spec:
  max:
    cpu: 384
    memory: 1536G
  min:
    cpu: 64
    memory: 256G
---
apiVersion: scheduling.x-k8s.io/v1alpha1
kind: ElasticQuota
metadata:
  name: tenant3
  namespace: tenant3
spec:
  max:
    cpu: 384
    memory: 1536G
  min:
    cpu: 32
    memory: 128G
---
apiVersion: scheduling.x-k8s.io/v1alpha1
kind: ElasticQuota
metadata:
  name: unused
  namespace: default
spec:
  max:
    cpu: 384
    memory: 1536G
  min:
    cpu: 160
    memory: 640G
---
apiVersion: scheduling.x-k8s.io/v1alpha1
kind: ElasticQuota
metadata:
  name: backfill
  namespace: backfill
spec:
  max:
    cpu: 384
    memory: 1536G
  min:
    cpu: 0
    memory: 0G
