apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenant1-nginx
  namespace: tenant1
spec:
  selector:
    matchLabels:
      app: tenant1-nginx
  template:
    metadata:
      labels:
        app: tenant1-nginx
    spec:
      schedulerName: scheduler-plugins-scheduler
      containers:
      - name: tenant1-nginx
        image: nginx
        ports:
        - name: http
          containerPort: 80
        resources:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 1
            memory: 2Gi
