#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: ConfigMap
metadata:
  name: yunikorn-configs
  namespace: yunikorn
data:
  queues.yaml: |
    partitions:
      - name: default
        queues:
        - name: root
          queues:
          - name: sandbox
            resources:
              max:
                {memory: 1536G, vcore: 384}
            queues:
            - name: tenants
              properties:
                #preemption.policy: fence
                preemption.delay: 1s
              queues:
              - name: tenant1
                submitacl: '*'
                resources:
                  guaranteed:
                    {memory: 256G, vcore: 128}
                properties:
                  priority.offset: "0"
              - name: tenant2
                submitacl: '*'
                resources:
                  guaranteed:
                    {memory: 128G, vcore: 64}
                properties:
                  priority.offset: "0"
              - name: tenant3
                submitacl: '*'
                resources:
                  guaranteed:
                    {memory: 64G, vcore: 32}
                properties:
                  priority.offset: "0"
              - name: tenant4
                submitacl: '*'
                resources:
                  guaranteed:
                    {memory: 2G, vcore: 1 }
                properties:
                  priority.offset: "-9999"
