apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: tenant1
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        applicationId: "test-nginx-01"
        queue: root.tenants.tenant1
    spec:
      schedulerName: yunikorn
      containers:
      - name: nginx
        image: nginx
        ports:
        - name: http
          containerPort: 80
        resources:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 1
            memory: 2Gi
